import Head from 'next/head'
import Image from 'next/image'
import SkHeader from '../components/SkHeader'
import SkSlider from '../components/SkSlider'
import SkServices from '../components/SkServices'
import SkSnapFeature from '../components/SkSnapFeature';
import SkBanner from '../components/SkBanner';
import SkPortfolio from '../components/SkPortfolio';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SkHeader />
      <SkSlider />
      <SkServices />
      <SkSnapFeature />
      <SkBanner />
      <SkPortfolio />
    </div>
  )
}
